### PR TITLE
Avoid calling non-namespaced hooks for ActiveJob compatibility.

### PR DESCRIPTION
**Pull request by dylanahsmith**
@jstorimer & @eapache for review

## Problem

[ActiveJob::Callbacks](https://github.com/rails/rails/blob/v4.2.0/activejob/lib/active_job/callbacks.rb) defines before_perform, after_perform, around_perform, before_enqueue, after_enqueue, and around_enqueue which get picked up by resque as plugin hooks.  This means that resque adds callbacks by calling these hooks on enqueuing and performing, and the `around_perform` method prevents the job from being performed, since it doesn't call yield.

## Solution

It is bad practice in resque to have non-namespaced hook methods.  It even has a lint check that enforces this.  As such, I just changed to method grep that resque does to not pick up non-namespaced methods, so the ActiveJob::Callbacks methods don't get picked up as resque hooks.

### CODE REVIEW

**Comment by eapache** [comment]
How does the official ActiveJob/Resque integration solve this problem?

**Comment by jstorimer** [comment]
Your changes look fine, but I'm curious about the same question that @eapache asked.

**Comment by dylanahsmith** [comment]
The official ActiveJob resque adapter uses a JobWrapper class, which will make the web UI a lot less readable, since every job will show up as being ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper.  There was an issue in the old activejob repo for this https://github.com/rails/activejob/issues/24, where DDH said:

> I’d almost rather that Sidekiq became clever enough to know that if the class is the JobWrapper, it should display the first argument instead as the class.

**Comment by dylanahsmith** [comment]
The JobWrapper class doesn't include ActiveJob::Callbacks, so doesn't have any resque hooks to call.  Since we actually depend on resque hooks still, that isn't even an option for us yet.

**Comment by eapache** [comment]
LGTM. I have grepped in shopify for functions not matching this pattern, and couldn't find any.

**Comment by dylanahsmith** [comment]
@fw42 Looks like we could workaround this issue if we could get https://github.com/resque/resque/commit/62ca48d521062cf703d4daa94cece8f930a46a10 backported to resque 1-x-stable, since it would allow the job class to define a class method named `hooks` which can provide a whitelist of methods to use as hook methods.

**Pull request merged**
