### PR TITLE
Merge upstream/1-x-stable

### PR DESCRIPTION
**Pull request by fw42**
This merges the upstream 1-x-stable branch into our master branch, to bring us [closer to upstream](https://github.com/Shopify/resque/compare/Shopify:db4d5d0d7c74bed0a57d3ba8443499ef8168c141...b3af72f792f4a590887fbffbc8a35d1ff48b6f06).

The remaining diff after merging would essentially be
* https://github.com/Shopify/resque/pull/1 (will PR this upstream: https://github.com/resque/resque/pull/1410).
* <s>https://github.com/Shopify/resque/commit/96f4ddb80f5842d6f43323f0076a2f9cdcb22b33 (see comments, not sure yet what to do here, maybe PR upstream).</s>

This PR basically reverted:
* https://github.com/Shopify/resque/pull/11/ (this fix was shitty, we should try something else).
* https://github.com/Shopify/resque/commit/4187877273371c1c620456dce4e67533f8d95be6. Looks like that's not necessary anymore since we can now use `GRACEFUL_TERM` to force `shutdown` in favour of `shutdown!`.

Hope I didn't forget anything. Will try out this branch on Shopify core CI.

Thoughts? @dylanahsmith @Sirupsen @burke @byroot 
FYI @steveklabnik

### CODE REVIEW

**Comment by fw42** [comment]
```
Finished tests in 1.943127s, 100.3537 tests/s, 218.2050 assertions/s.

195 tests, 424 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by burke** [comment]
> `shutdown!` is now the default

we were specifically overriding `shutdown!` to be `shutdown` though, because we pass `TERM` normally and want it to be graceful. Is that behaviour preserved?

**Comment by fw42** [comment]
@burke: it is if you set the `GRACEFUL_TERM` environment variable

**Comment by fw42** [comment]
@burke: I will make the necessary Shopify PR for that

**Comment by dylanahsmith** [comment]
> * https://github.com/Shopify/resque/commit/4187877273371c1c620456dce4e67533f8d95be6. Looks like that's not necessary anymore since `shutdown!` is now the default (unless `GRACEFUL_RESTART` is specified).

`shutdown!` was always the default.  We just need to set the `GRACEFUL_RESTART` environment variable where we are setting `BORG`.

**Comment by steveklabnik** [comment]
Thanks for the heads up. #1 looks good to me, I don't know about the SIGHUP stuff, as I don't really use Go or Docker, so I'll trust yinz's experiences with that.

**Comment by fw42** [comment]
(Shopify core CI is green with this ref)

**Comment by Sirupsen** [comment]
Nice Flo!

**Comment by steveklabnik** [comment]
:confetti_ball: 

I've been thinking about finally cutting a new release of Resque itself. Are there other things that you all are waiting for before using it? Should I wait for those things, or should we target another, smaller release after the current one?

**Comment by Sirupsen** [comment]
@steveklabnik we're about to put this in production, and then we'll report back! If all goes well, that should be a at least one good sign for a stable release :-)

**Comment by steveklabnik** [comment]
Excellent. I'm not in a rush, exactly, I just have some OSS time later this week :)

**Comment by fw42** [comment]
Yeah we are running the upstream 1-x-stable branch in production right now... Will monitor it for a while and let you know if anything seems fucky..

**Pull request merged**
